### ISSUE TITLE
Empty hosting package list in step 2

### ISSUE THREAD

**Issue by sasa-mladenovic-troxo** [atomia/AtomiaStore#1]
HostingPackage route query parameter in [RouteConfig](https://github.com/atomia/AtomiaStore/blob/master/Atomia.Store.Themes.Default/App_Start/RouteConfig.cs#L30) is incorrectly set to "HostingPackage" instead of "Hosting". This is also a problem in [SetupFeeCartPricingService.ProductCategoriesWithSetupFee](https://github.com/atomia/AtomiaStore/blob/master/Atomia.Store.PublicBillingApi/Adapters/SetupFeeCartPricingProvider.cs#L37).

This query string will eventually be set as parameter in 
[Atomia.Store.AspNetMvc.Controllers.ProductListingController.GetData()](https://github.com/atomia/AtomiaStore/blob/master/Atomia.Store.AspNetMvc/Controllers/ProductListingController.cs#L57)
which will eventually call 
[Atomia.Store.PublicBillingApi.ApiProductsProvider.GetProductsByCategories()](https://github.com/atomia/AtomiaStore/blob/master/Atomia.Store.PublicBillingApi/ApiProductsProvider.cs#L42)
With "HostingProducts" in categories function parameter.

First time this function is called, the call is forwarded to:
Atomia.Web.Plugin.ProductsProvider.PublicApiShopProductsProvider.GetProductsFromService().
In this function an API is called: [AtomiaBillingPublicService.GetShopProducts()](http://documentation.atomia.com/Billing/15.3.5700.13411/api-documentation/html/17c81fde-fd08-6794-b780-618e0c0ee9cd.htm) (this API call is probably better described [here](http://orderapi.dev.atomia.com/AtomiaBillingPublicService.asmx?op=GetShopProducts)) which returns a list of shop products. 

More acuratelly, it returns a list of Atomia.Web.Plugin.OrderServiceReferences.AtomiaBillingPublicService.PublicItem objects.
Problem here is that PublicItem.Category doesn't hold **shop category** name - but **product category** name.
So when code in Atomia.Web.Plugin.ProductsProvider.ProductsProviderBase.GetShopProductsByCategories() tries to filter shop products by category "HostingProducts" (that we gave as a function parameter) - it doesn't match product category 'Hosting" and returns empty product list in ApiProductsProvider.GetProductsByCategories().
And we end up with empty hosting package product list in step 2.

I did a workaround here and managed to replace "HostingPackage" with "Hosting" in my theme RouteConfig.RegisterRoutes() and it fixed my current issue. But I think that is not the right fix for this. 

Correct me if I'm wrong, but I think the point of using shop products is that you can add different type of products in the same shop category. For instance, I want to have both 'Hosting' product category and 'DNS' product category listed in the second step - so I can have DNS package (product category 'DNS') listed together with Platinum and Gold package (product category 'Hosting'). 
With this code we dont have that now - we can only filter products in the shop by their product category, instead of filtering it by their *shop category*.

**Comment by sasa-mladenovic-troxo** [comment]
Hmm, this looks like an issue with the Billing API version that I have on my test server. What is the minimum Billing API version that I need to have? What is the correct way to see a billing API version :) ?

**Comment by ivankustera** [comment]
Since @kdpersson is on vacation, I'll try to answer this. :)
This depends on branch of the Store you are using. If you are working with Store from master branch, you should have latest stable Billing API. If you are using development branch you should have latest test version of Billing API since this is version which has latest changes.

**Comment by sasa-mladenovic-troxo** [comment]
@ivankustera 
Thanks for replying ;)
I think the problem is in the version of the service that Store calls on this URL:

http://orderapi.dev.atomia.com/AtomiaBillingPublicService.asmx?op=GetShopProducts

That service call returns invalid 'Category' for shop products ('Domain' instead of 'TLD' and so on).
This service is installed by vagrant on my test - it is not related to the shop code I think.
I figured that I need to update that orderapi.dev.atomia.com code on my master computer installed by vagrant. 

One more thing to note - I changed orderapi.dev.atomia.com to orderapi.test.fxwcloud.nl (our clients server) in Web.config (AtomiaBillingPublicService.Url) and it started to return the correct TLD.

I will update my test server and I think it will start to work. However, it would be good to know minimum version that I need to install on orderapi server for Store to work properly.

**Comment by ivankustera** [comment]
Order API is in Billing API package so the same rule applies.

**Comment by kdpersson** [comment]
Just to confirm what @ivankustera has said above. The master branch should be used with Billing API 15.3 and the dev-15.9 branch should be used with Billing API 15.9

Since our vagrant env is running 15.9 by default I can see how this was confusing. I will soon merge dev-15.9 into master and then master should work with the default vagrant env out of the box.

I will make a note to add version requirements to the README.
