### ISSUE TITLE
Error updating theme (error MSB4019)

### ISSUE THREAD

**Issue by sasa-mladenovic-troxo** [atomia/AtomiaStore#16]
Hi,

I follwed [instructions](https://github.com/atomia/AtomiaStore/blob/master/Documentation/getting-started-with-a-new-theme.md#updating-lib-and-default-theme-files) in order to upgrade my theme. But when I run the: `AtomiaStore\ThemeStarter\updatetheme.ps1 <ThemePath>` command I got the error:
```
"C:\work\atomia\AtomiaStore\Solution\Store.sln" (rebuild target) (1) ->
"C:\work\atomia\AtomiaStore\Atomia.Store.Themes.Default\Atomia.Store.Themes.Default.csproj" (Rebuild target) (2) ->
  C:\work\atomia\AtomiaStore\Atomia.Store.Themes.Default\Atomia.Store.Themes.Default.csproj(473,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication .targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```
I searched a little about the error and it looks like the issue happens because MSBuild is now shipped with Visual Studio as of version 2013 (more info [here](https://blogs.msdn.microsoft.com/visualstudio/2013/07/24/msbuild-is-now-part-of-visual-studio/), [here](http://timrayburn.net/blog/visual-studio-2013-and-msbuild/) and [here](http://stackoverflow.com/a/26443520)).

I updated [updatetheme.ps1](https://github.com/atomia/AtomiaStore/blob/master/ThemeStarter/updatetheme.ps1) and replaced:
```
$msbuild = "$($Env:SystemRoot)\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe"
```
with
```
$msbuild = "C:\Progra~2\MSBuild\12.0\Bin\MSBuild.exe"
```
which fixed the error.

I'm not exactly sure that my solution is the correct one, so I'm posting here in case you have better solution.

**Comment by kdpersson** [comment]
Long time coming, but this is now fixed for both updatetheme.ps
