### ISSUE TITLE
Extending or adding new controller or changing model validation regular expresion

### ISSUE THREAD

**Issue by sasa-mladenovic-troxo** [atomia/AtomiaStore#2]
Hi,

what is the easiest way to extend or add new controller when customizing Store?

I need to allow domain search for multiple search strings at once: "mindomain.com mindoman.net".
Default implementation of DomainsController.FindDomains() is not allowing such strings - validation fails.

Maybe I could change the regular expresion for DomainQueryModel.Query?

**Comment by kdpersson** [comment]
You should be able to just add a class that inherits `System.Web.Mvc.Controller` to your customization project, and it should be registered automatically. If you want a specific route you can also add and entry to your `RouteConfig.cs`.

I would not recommend changing the regular expression.

I will look in to making the existing `FindDomains` action handle multiple search strings, or add another action for that.

**Comment by sasa-mladenovic-troxo** [comment]
> You should be able to just add a class that inherits `System.Web.Mvc.Controller` to your customization project, and it should be registered automatically. If you want a specific route you can also add and entry to your `RouteConfig.cs`.

This worked just fine ;)

Minor issue is that all Store controllers are `sealed`, so instead of extending the existing controller and adding just one more action - I have to copy-paste the whole class.

**Comment by kdpersson** [comment]
I have opted to seal things as the default in many cases to avoid maintainability problems down the line. If it seems some sealed classes are generally usefull as base classes we'll see about opening them up and making sure they are built to support extension longterm.

**Comment by sasa-mladenovic-troxo** [comment]
I agree. Copy-paste is not dificult.
I think we can close this issue.
