### ISSUE TITLE
Invalid path to images in theme.css

### ISSUE THREAD

**Issue by sasa-mladenovic-troxo** [atomia/AtomiaStore#3]
Hi,

I published my theme and I copied contents of publish folder on store installation on my client server.
But when I open the shop url - all images from `theme.css` have invalid path.
For instance, I have in my `theme.css`
`background: url(../img/header-fwh.png);`

Which, in my local test, transforms to 
[http://localhost:44982/Themes/Flex/Content/img/header-fwh.png](http://localhost:44982/Themes/Flex/Content/img/header-fwh.png)

but on client server it transforms to:
https://store.test.fxwcloud.nl/Themes/Default/Content/css/img/header-fwh.png

If I update on client server Web.config debug with:
`<compilation debug="true" targetFramework="4.0" />`

Than I get ok url after refresh:
https://store.test.fxwcloud.nl/Themes/Flex/Content/img/header-fwh.png

Am I missing something here? Do I really need to set this in css:
`background: url(../../../../Flex/Content/img/header-fwh.png);`

Same thing is happening with google fonts. 
I have in header tpl set:
`<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Share+Tech" type="text/css">`
and in `theme.css`:
`font-family: 'Share Tech', Arial, sans-serif;`
This font is loaded fine when in debug mode on client server, but falls back to Arial when it's not a debug mode.

**Comment by kdpersson** [comment]
Have you taken into account for the non-debug version is that the `StyleBundle` gets its own path set in `BundleConfig.cs`? I have found it to be least problematic to keep that path the same as the actual file path of the theme css, as you can see in the `BundleConfig.cs` for the default theme.

The font issue I am not sure about, it seems less likely to be related to this, but give the above a try and see if it solves that as well.

**Comment by sasa-mladenovic-troxo** [comment]
Thanks, your answer made me change the default bundle configuration in my theme `BundleConfig.cs` to add a separate bundle instead of extending existing bundle you made in default theme 
So, the code is now:

            var scriptBundle = bundles.GetBundleFor(Atomia.Store.Themes.Default.BundleConfig.DEFAULT_SCRIPTS_BUNDLE);
            scriptBundle.IncludeDirectory("~/Themes/Flex/Scripts", "*.js");
            var styleBundle = bundles.GetBundleFor(Atomia.Store.Themes.Default.BundleConfig.DEFAULT_STYLES_BUNDLE);
            var styleBundleFlex = new StyleBundle("~/Themes/Flex/Content/css/theme")
                .Include(
                    "~/Themes/Flex/Content/css/theme.css");
            bundles.Clear();
            bundles.Add(scriptBundle);
            bundles.Add(styleBundle);
            bundles.Add(styleBundleFlex);

As for the font issue - that was not related to this, it was related to this error:
`store.test.fxwcloud.nl/:17 Mixed Content: The page at 'https://store.test.fxwcloud.nl/?lang=EN-US' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Share+Tech'. This request has been blocked; the content must be served over HTTPS.`

Changing `http` to `https` in link tag fixed the issue.

I think we can close this one too ;)
