### ISSUE TITLE
How to fetch VAT number for existing customer

### ISSUE THREAD

**Issue by sasa-mladenovic-troxo** [atomia/AtomiaStore#6]
In our Atomia Store customization we have a third step where you can enter address data for new customer or you can enter username and password of existing customer. Later we place an order to existing customer if username/pwd is used. If this existing customer has a valid VAT number, invoice created for his new order will not have zero tax amount in accordance to the existing tax rule.

Problem is that cart and invoice preview on the checkout page will display non-zero tax amount for this existing customer. Even worse, if this existing customer decides to pay via credit card - the amount used will include non-zero tax amount also.

I couldn't find any function in [AtomiaBillingPublicService ](http://documentation.atomia.com/Billing/latest/api-documentation/html/45295e79-aa8e-cc98-b4c5-5a5bab16b8be.htm) that can return VAT number for existing customer.

What is the best way to get existing customer VAT number in atomia store? I was thinking to use full [AtomiaBillingApi](http://documentation.atomia.com/Billing/latest/api-documentation/html/6adc9566-c0b2-e049-ec81-44d9df6d0f00.htm) for this (method [GetAccountById()](http://documentation.atomia.com/Billing/latest/api-documentation/html/c28d37c2-1cb7-9be3-f4ea-184bf971654d.htm) looks promising), but there may be some security issues with that?

**Comment by kdpersson** [comment]
That seems like an oversight in the API. It should really be returned somewhere like AccountInfo in ValidateUser. I will propose that fix, but since it is an API change it will not be available until the 16.3 release.

In the meantime, your suggested solution to use AtomiaBillingApi via Atomia.Web.Plugin.ServiceReferences is fine.

**Comment by ivan-milovanovic-troxo** [comment]
Calling Atomia.Web.Plugin.ServiceReferences.AtomiaServiceChannelManager.GetBilingService() which should return instance of Billing Api produces following error: Unable to find client token. Check if your ServiceHost is correctly configured.

![Unable to find client token. Check if your ServiceHost is correctly configured.](https://cloud.githubusercontent.com/assets/11176348/10193499/cd0e6704-6783-11e5-9baa-f11fd671ad7c.png)

How can we configure ServiceHost correctly?

**Comment by ivankustera** [comment]
This is sorted out with @sasa-mladenovic-troxo

**Comment by sasa-mladenovic-troxo** [comment]
Transformation file related to the Web.config changes:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
	<cachingConfiguration defaultCacheManager="ProductsCache">
			<cacheManagers>
			  <add name="Token Cache Manager" type="Microsoft.Practices.EnterpriseLibrary.Caching.CacheManager, Microsoft.Practices.EnterpriseLibrary.Caching, Version=5.0.414.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" expirationPollFrequencyInSeconds="120" maximumElementsInCacheBeforeScavenging="1000" numberToRemoveWhenScavenging="10" backingStoreName="NullBackingStore"  xdt:Transform="Insert" />
			</cacheManagers>
	</cachingConfiguration>
    <atomiaCommon xmlns="atomia.com">
	  <executionContext fallback="true" lifetimeManager="Atomia.Common.AspExecutionContextLifetimeManager, Atomia.Common" xdt:Transform="Replace" xdt:Locator="Match(fallback)" />
	</atomiaCommon>
</configuration>
```
We also had to add `Atomia.Web.Plugin.ServiceReferences.dll.config` (which is completely missing in Store Lib folder). And we had to add `Microsoft.IdentityModel.dll` to the Lib folder and project as a reference.

In addition I needed to call the code for fetching Billing service with the `false` parameter:
`Atomia.Web.Plugin.ServiceReferences.AtomiaServiceChannelManager.GetBilingService(false)`

I think we can close this issue now.
